### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by Phlogi** [Goldfish64/DiskArbitrationFixup#1]
Could you please add some short build instructions? How do I make sure that this plugin finds the headers from lilu? 
Alternative: Create a kext as release please.

**Comment by Goldfish64** [comment]
A debug build of Lilu.kext should be placed in the root of the cloned repo, just like other Lilu plugins.

**Comment by Phlogi** [comment]
Thanks, this works and also the kext itself works as expected!
