### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by HelmoHass** [Goldfish64/DiskArbitrationFixup#2]
Hi.
just wanted to report that the plugin fail to build with new version of Lilu 1.4.0

tested with version 1.3.9 and it build successfully...
[DiskArbitrationFixup.log](https://github.com/Goldfish64/DiskArbitrationFixup/files/3893669/DiskArbitrationFixup.log)

**Comment by Goldfish64** [comment]
Should be fixed. Thanks.
